### ISSUE TITLE
[Question] Is there a Microsoft.Extensions.Logging equivalent for this package?

### ISSUE THREAD

**Issue by jzabroski** [teo-tsirpanis/serilog-sinks-msbuild#1]
I am searching for a package as my  code (FluentMigrator) depends on Microsoft.Extensions.Logging and not Serilog, and I am trying to debug an issue in FluentMigrator.MSBuild.

**Comment by teo-tsirpanis** [comment]
Thanks for opening this issue. I couldn't find such package but I noticed you already created [an MSBuild logger](https://github.com/fluentmigrator/fluentmigrator/blob/main/src/FluentMigrator.MSBuild/MicrosoftBuildLogger.cs) in `FluentMigrator.MSBuild` so I'm going to close this issue as out of scope for this project.

I might in the future write an `ILoggerProvider` for MSBuild, depending on my personal projects' needs and free time, and I will let you know if I do it.

**Comment by jzabroski** [comment]
Yes, acts of necessity.  Mine stinks compared to yours but I just needed some basics to get started.
